### ISSUE TITLE
Reset pin not connected ?

### ISSUE THREAD

**Issue by ghost** [PiInTheSky/pits-hardware#1]
Hello,

I have some reliability issues with the LoRa gateway board with RPi 3 (Hope RF 96/98). It seems that the communication is failing randomly and I'm guessing this could be due to the floating reset pin. Does this pin has been left unconnected for some good reasons ?

Vincent

**Comment by Upuaut** [comment]
We did a revision where the reset pin was connected to a GPIO but it was unstable. We've seen no issues leaving it floating. If you bought the board through Uputronics send us a mail with your order number and we'll replace it.
